# Ad-hoc (self-signed, local-trust-only) code signing for the Windows build.
#
# This is NOT the same as a real Authenticode signature from a CA-issued
# certificate - Windows SmartScreen and other machines will still flag the
# binary as from an "Unknown Publisher" unless you later buy a real code-
# signing certificate. What this DOES give you: a signed binary with
# "Sprizzle" as the subject in its digital signature properties, useful for
# local testing / internal distribution where you control the machine (or
# can add the self-signed cert to Trusted Root/Trusted Publishers yourself).
#
# UNVERIFIED - run and debug on an actual Windows machine. Needs signtool.exe,
# which ships with the Windows SDK; easiest is to run this from a
# "Developer PowerShell for VS" prompt where it's already on PATH.
param(
    [string]$VstPath = "dist\windows\HallucinatorRAVE.vst3",
    [string]$CertSubject = "CN=Sprizzle, O=Sprizzle, E=spryte@sprizzle.io"
)
$ErrorActionPreference = "Stop"
Set-Location (Split-Path -Parent $PSScriptRoot)

$signtool = Get-Command signtool.exe -ErrorAction SilentlyContinue
if (-not $signtool) {
    Write-Error "signtool.exe not found on PATH. Run this from a 'Developer PowerShell for VS' prompt, or add the Windows SDK's bin dir to PATH."
    exit 1
}

# Reuse an existing Sprizzle cert if one was already generated by a previous
# run, instead of minting a new one (and a new, different Trusted-Publisher
# decision) every time.
$existing = Get-ChildItem Cert:\CurrentUser\My -CodeSigningCert |
    Where-Object { $_.Subject -eq $CertSubject } |
    Select-Object -First 1

if ($existing) {
    $cert = $existing
    Write-Host "Reusing existing self-signed cert: $($cert.Thumbprint)"
} else {
    $cert = New-SelfSignedCertificate `
        -Type CodeSigningCert `
        -Subject $CertSubject `
        -CertStoreLocation Cert:\CurrentUser\My `
        -KeyUsage DigitalSignature `
        -FriendlyName "Sprizzle (ad-hoc, local test signing only)" `
        -NotAfter (Get-Date).AddYears(3)
    Write-Host "Created new self-signed cert: $($cert.Thumbprint)"
    Write-Host "To have this machine trust it (so Windows won't flag it as untrusted"
    Write-Host "locally), also import it into Cert:\CurrentUser\TrustedPublisher and"
    Write-Host "Cert:\LocalMachine\Root - that step is deliberately not automated here"
    Write-Host "since it affects what your OS trusts beyond just this plugin."
}

if (-not (Test-Path $VstPath)) {
    Write-Error "$VstPath not found - build and package dist\windows first."
    exit 1
}

# Sign every PE binary under the bundle - JUCE's Windows VST3 output may be
# a single .vst3 file or a Contents\x86_64-win\*.vst3 bundle depending on
# version/settings; this covers both without assuming which.
$targets = Get-ChildItem -Path $VstPath -Recurse -Include *.vst3, *.dll -File
if (-not $targets) {
    Write-Error "No .vst3/.dll files found under $VstPath"
    exit 1
}

foreach ($file in $targets) {
    & signtool.exe sign /sha1 $cert.Thumbprint /fd sha256 /tr http://timestamp.digicert.com /td sha256 "$($file.FullName)"
}

Write-Host ""
Write-Host "Signed. Verify with:"
Write-Host "  signtool verify /pa `"$VstPath`""
Write-Host "(expect a warning about the root not being trusted, unless you did the"
Write-Host "TrustedPublisher/Root import step above - that's expected for ad-hoc signing.)"
